[package]
name = "schema_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = { version = "0.37.0", features = ["serialize"] }
reqwest = { version = "0.12", features = ["blocking"] }
serde = { version = "1.0.207", features = ["derive"] }
serde_json = "1.0.124"
serde-xml-rs = "0.6.0"
regex = "1.11.1"